### ISSUE TITLE
Curious what you're using this for.

### ISSUE THREAD

**Issue by ryanrdetzel** [magcode/mopidy-mqtt#5]
I want to make changes that won't be backward compatible. I'm fine with maintaining my own repo but depending on how you use it the changes might be useful for you too. Just curious how you're using or plan to use this.

**Comment by magcode** [comment]
Hello Ryan,

The whole thing has been started once I needed to integrate Mopidy into my Home Automation (Openhab). I only needed/need a fraction of features.
However I don't mind bringing it forward. Would even like to list it here: https://docs.mopidy.com/en/latest/ext/frontends/ once we have a stable and clean codebase.

So... are the targeted changes regarding the MQTT topic structure?

If it breakes compatibility, no problem. We just add it to the readme.

**Comment by magcode** [comment]
btw. In case it is about MQTT look here: https://github.com/Informatic/mopidy-mqtt/commit/df83289aa2455009dd2842b3e1814afbdcdef952

https://github.com/marvinroger/homie

Has never been PRed

**Comment by Jenscaasen** [comment]
Hello, i am very eager to use this, it is up and running, thanks for this! But i can't figure out what to post to make it play a local file or playlist. Start / stop works, what what is the term to send to start a playlist? Sorry for abusing this to ask a question

**Comment by magcode** [comment]
no worries @Jenscaasen 

as described in the readme

`mytopic/play -> 'tunein:station:s48720'`

for a DNLA server
`mytopic/play -> dleyna://uuid%3a84052123-d4a8-3050-acdd-7d9fca8e4d8a/415f465e464f4c2a5233244631303833`

local files will be something like `local:path-to-file`. I don't use local files so never tested it.
(see https://docs.mopidy.com/en/latest/ext/local/)

playlists - no idea. If you have such a playlist and some mopidy frontend running you can check in your browser dev console what happens if you click on the playlist. This is how I found out the tunein/dleyna examples.

**Comment by Jenscaasen** [comment]
Thanks for the examples!
I also already found out that the web add-on "iris" provides this "copy URI" option, which copys what you need to send with "/play". That worked for me with single local files. local m3u playlists did not work, might be a problem with my setup. Then i checked spotify implementation.
Playlist from spotify do not work, own ones do, they look like this:
spotify:user:username:playlist:SomeGuid
Own playlists only play the first song though.
YOu can see the whole URI in the URL of the spotify webplayer, just replace the "/" with ":" and add "spotify:" in front. 

Playing artists also work:
spotify:artist:someGuid

Again, someGuid is from the URL online. Artists even play multiple songs.

Now going for the next big step: figuring out how to send MQTT from openHAB :S 

Thanks for this plugin! :-)

**Comment by LEDTECHCHGO** [comment]
is their a list of all commands i can get play stop status nopwplay working are others any others
